name: Mrotok Activity

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:      

permissions:
  contents: write

jobs:
  activity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update file
        run: |
          echo "Update: $(date)" > IJOMROTOK

      - name: Commit and Push
        run: |
     
          git config --global user.name "Jenderal92"
          git config --global user.email "59664965+Jenderal92@users.noreply.github.com"
          
          git add IJOMROTOK
          
          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "chore: update contribution $(date)"
            git push origin main
          fi
