name: Mrotok Activity

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  activity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update file
        run: |
          echo "Update $(date)" > IJOMROTOK

      - name: Commit
        run: |
          git config --global user.name "activity-bot"
          git config --global user.email "activity@github.com"
          git add IJOMROTOK
          git commit -m "update activity $(date)" || echo "no change"

      - name: Push
        run: git push
